### ISSUE TITLE
Doesn't work on Firefox Windows

### ISSUE THREAD

**Issue by sniljulabs** [gautamkrishnar/motrix-webextension#148]
I have Windows 11 and Firefox with Motrix Enabled. I tried all the methods to make it work but it simply won't work! I tried changing the RPC keys port and set those on the browser extension but failed! I'm using the latest version of firefox as of 11/9/2024!

**Comment by scombs90** [comment]
Yep, same deal. Tried a number of different methods. Despite correct configuration, won't pass any download.

**Comment by magbulogtong81** [comment]
I had that same issue, but I'm on linux mint. however, I think it's the same issue so you could try this:

on firefox, open motrix extension then click the power button so that it turns green. then restart firefox (close it and open it again).
open Motrix if you haven't open it yet. then try to download something in firefox


restarting firefox to make it work is kind of inconvenient and misleading though. A user would expect that it will just work right away

**Comment by alrcatraz** [comment]
I use Zen Browser, which is also a Firefox web browser. It doesn't work even after restarting the the browser, so I'm not sure if there are other issues.

**Comment by rmansour** [comment]
> I use Zen Browser, which is also a Firefox web browser. It doesn't work even after restarting the the browser, so I'm not sure if there are other issues.

Same here, doesn't work even after restart

**Comment by gautamkrishnar** [comment]
Hi, guys I just released a newer version of the extension that fixes some bugs on Firefox. Let me know if it works fine now after updating the extension.

**Comment by rmansour** [comment]
> Hi, guys I just released a newer version of the extension that fixes some bugs on Firefox. Let me know if it works fine now after updating the extension.

Still not working with Zen Browser, it downloads neither through the browser extension nor through the desktop app. 
Thanks for your work!

**Comment by gautamkrishnar** [comment]
@rmansour unfortunately it's hard to support all the browser variants. Thanks for confirming it's working with Firefox.

**Comment by rmansour** [comment]
> [@rmansour](https://github.com/rmansour) unfortunately it's hard to support all the browser variants. Thanks for confirming it's working with Firefox.

@gautamkrishnar - a small update: after the latest Zen Browser update, it looks like the download using Motrix is working correctly, albeit only after the prompt to choose the save location for the file to be downloaded.
Not sure if it was the update that made it work or not.
